name: C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make g++ cmake

    # Step 3: Build the project using Makefile
    - name: Build with Make
      run: |
        make
        make test
        make clean
      
    # Step 4: Build the project using CMake
    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
        ctest --output-on-failure
        make clean

    # For extensive debugging, replace 'Release' with 'Debug' in 'cmake ..' command of Step 4.